### PR TITLE
fluent api, refeactored tests, updated core, removing plus sign

### PR DESCRIPTION
**Pull request by bgalek**
I introduced new fluent api, so if it is ok with you, remember to change major version number ;)
Hope you like it! :)

### CODE REVIEW

**Comment by bgalek** [comment]
any chances to review this pr? :)

**Comment by dtrunk90** [comment]
I'll try to take a look at it this weekend

**Comment by bgalek** [comment]
any chances this weekend?:)

**Comment by bgalek** [comment]
added performance tweak ;)

**Comment by dtrunk90** [comment]
I'd like to merge your PR. There's just one point: Could you please replace the tabs with spaces? In my opinion tabs are better than spaces because everyone can set the width of a tab if someone can't easily read code with 4 spaces indentation.

**Comment by bgalek** [comment]
Glad to hear that! I've changed spaces to tabs as you wanted ;)

**Comment by dtrunk90** [comment]
There are still spaces in InitSlugifyTag.java ;-)

**Comment by bgalek** [comment]
damn, missed the file ;) 
update pushed

**Comment by dtrunk90** [comment]
Thanks for your efforts. I'll make a new release asap.

**Comment by dtrunk90** [comment]
2.1.6 is released now. Thanks again.

**Comment by bgalek** [comment]
Thank you too! :)

pon., 22.08.2016, 19:44 użytkownik Danny Trunk <notifications@github.com>
napisał:

**Pull request merged**
