### PR TITLE
Migrates library to Java 8

### PR DESCRIPTION
**Pull request by jzimermann**
The intent of this Pull Request is to migrate the source code of this library to use Java 8. The build process was supporting Java 7+ but not taking advantage of it so this PR removes the support for Java 7. 

The migration itself does not only any feature change but improves the developer experience by providing access to newer features, like lambda expressions and etc.

I also added some refactoring mainly around extracting constants and replacing loops by lambdas.

Hope it helps to improve this codebase 😃

### CODE REVIEW

**Comment by dtrunk90** [comment]
Thanks for your efforts. Could you please change the spaces back to tabs as well as adding the current openjdk to the travis list? I would like to ensure support for the open source variant.

**Comment by jzimermann** [comment]
@dtrunk90 thanks for the feedback! I updated the PR to fix the `tab` issues (I hope I'm now using the same as you use). 

I'm afraid though it won't be possible to keep `openjdk7 ` on the list of builds once the migration to Java 8 happen. Travis is trying to build the library using Java 8 features on a JDK with Java 7, causing compilation's issues.

Do you feel it's really necessary making it compatible with Java 7, 8 and 9 at the same time?

**Comment by dtrunk90** [comment]
Not Java 7, 8 and 9 but Java >= 8 for Oracles JDK and OpenJDK.

**Comment by dtrunk90** [comment]
Version 2.2 is released now. Thanks again.

**Pull request merged**
